START TRANSACTION;
CREATE TABLE "Iocs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Sha256" text NOT NULL,
    "Sha1" text NOT NULL,
    "Md5" text NOT NULL,
    "Mcafee" text NOT NULL,
    "Engines" text NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedOn" timestamp with time zone,
    "CreatedById" integer,
    "UpdatedById" integer,
    CONSTRAINT "PK_Iocs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Iocs_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id"),
    CONSTRAINT "FK_Iocs_Users_UpdatedById" FOREIGN KEY ("UpdatedById") REFERENCES "Users" ("Id")
);

CREATE INDEX "IX_Iocs_CreatedById" ON "Iocs" ("CreatedById");

CREATE INDEX "IX_Iocs_UpdatedById" ON "Iocs" ("UpdatedById");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250531181741_AddIocTable', '9.0.5');

COMMIT;

