-- Insert Admin role if it doesn't exist
IF NOT EXISTS (
    SELECT 1
FROM [Roles]
WHERE [NormalizedName] = 'ADMIN'
)
BEGIN
    INSERT INTO [Roles]
        ([Name], [NormalizedName], [IsDeleted], [CreatedOn])
    VALUES
        ('Admin', 'ADMIN', 0, GETDATE())
END

-- Insert admin user if it doesn't exist
IF NOT EXISTS (
    SELECT 1
FROM [Users]
WHERE [NormalizedEmail] = 'ADMIN@EXAMPLE.COM'
)
BEGIN
    INSERT INTO [Users]
        (
        [UserName], [NormalizedUserName], [Email], [NormalizedEmail], [EmailConfirmed],
        [IsDeleted], [CreatedOn], [PasswordHash], [State],
        [PhoneNumberConfirmed], [TwoFactorEnabled], [LockoutEnabled], [AccessFailedCount]
        )
    VALUES
        (
            'admin@example.com', 'ADMIN@EXAMPLE.COM', 'admin@example.com', 'ADMIN@EXAMPLE.COM', 1,
            0, GETDATE(),
            -- Replace with a real hash generated by ASP.NET Identity for your password
            'AQAAAAIAAYagAAAAEI+EmETzACYw/Xz0bLyJ1A2DiE7+vKTpAFLst1YxbT1D9Ud+WRSkS1YNGLKbOZ8mtA==',
            1, -- State
            0, -- PhoneNumberConfirmed
            0, -- TwoFactorEnabled
            0, -- LockoutEnabled
            0  -- AccessFailedCount
    )
END

-- Assign admin user to Admin role
IF EXISTS (
    SELECT 1
    FROM [Users]
    WHERE [NormalizedEmail] = 'ADMIN@EXAMPLE.COM'
)
    AND EXISTS (
    SELECT 1
    FROM [Roles]
    WHERE [NormalizedName] = 'ADMIN'
)
    AND NOT EXISTS (
    SELECT 1
    FROM [UserRoles] ur
        INNER JOIN [Users] u ON ur.[UserId] = u.[Id]
        INNER JOIN [Roles] r ON ur.[RoleId] = r.[Id]
    WHERE u.[NormalizedEmail] = 'ADMIN@EXAMPLE.COM' AND r.[NormalizedName] = 'ADMIN'
)
BEGIN
    INSERT INTO [UserRoles]
        ([UserId], [RoleId], [IsDeleted], [CreatedOn])
    SELECT u.[Id], r.[Id], 0, GETDATE()
    FROM [Users] u, [Roles] r
    WHERE u.[NormalizedEmail] = 'ADMIN@EXAMPLE.COM'
        AND r.[NormalizedName] = 'ADMIN'
END